<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('tests', ['as'=> 'tests.index', 'uses' => 'TestController@index']);
Route::post('tests', ['as'=> 'tests.store', 'uses' => 'TestController@store']);
Route::get('tests/create', ['as'=> 'tests.create', 'uses' => 'TestController@create']);
Route::put('tests/{tests}', ['as'=> 'tests.update', 'uses' => 'TestController@update']);
Route::patch('tests/{tests}', ['as'=> 'tests.update', 'uses' => 'TestController@update']);
Route::get('tests/{id}/delete', array('as' => 'tests.delete', 'uses' => 'TestController@getDelete'));
Route::get('tests/{id}/confirm-delete', array('as' => 'tests.confirm-delete', 'uses' => 'TestController@getModalDelete'));
Route::get('tests/{tests}', ['as'=> 'tests.show', 'uses' => 'TestController@show']);
Route::get('tests/{tests}/edit', ['as'=> 'tests.edit', 'uses' => 'TestController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('tests', ['as'=> 'tests.index', 'uses' => 'TestController@index']);
Route::post('tests', ['as'=> 'tests.store', 'uses' => 'TestController@store']);
Route::get('tests/create', ['as'=> 'tests.create', 'uses' => 'TestController@create']);
Route::put('tests/{tests}', ['as'=> 'tests.update', 'uses' => 'TestController@update']);
Route::patch('tests/{tests}', ['as'=> 'tests.update', 'uses' => 'TestController@update']);
Route::get('tests/{id}/delete', array('as' => 'tests.delete', 'uses' => 'TestController@getDelete'));
Route::get('tests/{id}/confirm-delete', array('as' => 'tests.confirm-delete', 'uses' => 'TestController@getModalDelete'));
Route::get('tests/{tests}', ['as'=> 'tests.show', 'uses' => 'TestController@show']);
Route::get('tests/{tests}/edit', ['as'=> 'tests.edit', 'uses' => 'TestController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('articles', ['as'=> 'articles.index', 'uses' => 'ArticleController@index']);
Route::post('articles', ['as'=> 'articles.store', 'uses' => 'ArticleController@store']);
Route::get('articles/create', ['as'=> 'articles.create', 'uses' => 'ArticleController@create']);
Route::put('articles/{articles}', ['as'=> 'articles.update', 'uses' => 'ArticleController@update']);
Route::patch('articles/{articles}', ['as'=> 'articles.update', 'uses' => 'ArticleController@update']);
Route::get('articles/{id}/delete', array('as' => 'articles.delete', 'uses' => 'ArticleController@getDelete'));
Route::get('articles/{id}/confirm-delete', array('as' => 'articles.confirm-delete', 'uses' => 'ArticleController@getModalDelete'));
Route::get('articles/{articles}', ['as'=> 'articles.show', 'uses' => 'ArticleController@show']);
Route::get('articles/{articles}/edit', ['as'=> 'articles.edit', 'uses' => 'ArticleController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('articles', ['as'=> 'articles.index', 'uses' => 'ArticleController@index']);
Route::post('articles', ['as'=> 'articles.store', 'uses' => 'ArticleController@store']);
Route::get('articles/create', ['as'=> 'articles.create', 'uses' => 'ArticleController@create']);
Route::put('articles/{articles}', ['as'=> 'articles.update', 'uses' => 'ArticleController@update']);
Route::patch('articles/{articles}', ['as'=> 'articles.update', 'uses' => 'ArticleController@update']);
Route::get('articles/{id}/delete', array('as' => 'articles.delete', 'uses' => 'ArticleController@getDelete'));
Route::get('articles/{id}/confirm-delete', array('as' => 'articles.confirm-delete', 'uses' => 'ArticleController@getModalDelete'));
Route::get('articles/{articles}', ['as'=> 'articles.show', 'uses' => 'ArticleController@show']);
Route::get('articles/{articles}/edit', ['as'=> 'articles.edit', 'uses' => 'ArticleController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('articlezs', ['as'=> 'articlezs.index', 'uses' => 'ArticlezController@index']);
Route::post('articlezs', ['as'=> 'articlezs.store', 'uses' => 'ArticlezController@store']);
Route::get('articlezs/create', ['as'=> 'articlezs.create', 'uses' => 'ArticlezController@create']);
Route::put('articlezs/{articlezs}', ['as'=> 'articlezs.update', 'uses' => 'ArticlezController@update']);
Route::patch('articlezs/{articlezs}', ['as'=> 'articlezs.update', 'uses' => 'ArticlezController@update']);
Route::get('articlezs/{id}/delete', array('as' => 'articlezs.delete', 'uses' => 'ArticlezController@getDelete'));
Route::get('articlezs/{id}/confirm-delete', array('as' => 'articlezs.confirm-delete', 'uses' => 'ArticlezController@getModalDelete'));
Route::get('articlezs/{articlezs}', ['as'=> 'articlezs.show', 'uses' => 'ArticlezController@show']);
Route::get('articlezs/{articlezs}/edit', ['as'=> 'articlezs.edit', 'uses' => 'ArticlezController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('newDatas', ['as'=> 'newDatas.index', 'uses' => 'NewDataController@index']);
Route::post('newDatas', ['as'=> 'newDatas.store', 'uses' => 'NewDataController@store']);
Route::get('newDatas/create', ['as'=> 'newDatas.create', 'uses' => 'NewDataController@create']);
Route::put('newDatas/{newDatas}', ['as'=> 'newDatas.update', 'uses' => 'NewDataController@update']);
Route::patch('newDatas/{newDatas}', ['as'=> 'newDatas.update', 'uses' => 'NewDataController@update']);
Route::get('newDatas/{id}/delete', array('as' => 'newDatas.delete', 'uses' => 'NewDataController@getDelete'));
Route::get('newDatas/{id}/confirm-delete', array('as' => 'newDatas.confirm-delete', 'uses' => 'NewDataController@getModalDelete'));
Route::get('newDatas/{newDatas}', ['as'=> 'newDatas.show', 'uses' => 'NewDataController@show']);
Route::get('newDatas/{newDatas}/edit', ['as'=> 'newDatas.edit', 'uses' => 'NewDataController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('payments', ['as'=> 'payments.index', 'uses' => 'PaymentController@index']);
Route::post('payments', ['as'=> 'payments.store', 'uses' => 'PaymentController@store']);
Route::get('payments/create', ['as'=> 'payments.create', 'uses' => 'PaymentController@create']);
Route::put('payments/{payments}', ['as'=> 'payments.update', 'uses' => 'PaymentController@update']);
Route::patch('payments/{payments}', ['as'=> 'payments.update', 'uses' => 'PaymentController@update']);
Route::get('payments/{id}/delete', array('as' => 'payments.delete', 'uses' => 'PaymentController@getDelete'));
Route::get('payments/{id}/confirm-delete', array('as' => 'payments.confirm-delete', 'uses' => 'PaymentController@getModalDelete'));
Route::get('payments/{payments}', ['as'=> 'payments.show', 'uses' => 'PaymentController@show']);
Route::get('payments/{payments}/edit', ['as'=> 'payments.edit', 'uses' => 'PaymentController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('payments', ['as'=> 'payments.index', 'uses' => 'PaymentController@index']);
Route::post('payments', ['as'=> 'payments.store', 'uses' => 'PaymentController@store']);
Route::get('payments/create', ['as'=> 'payments.create', 'uses' => 'PaymentController@create']);
Route::put('payments/{payments}', ['as'=> 'payments.update', 'uses' => 'PaymentController@update']);
Route::patch('payments/{payments}', ['as'=> 'payments.update', 'uses' => 'PaymentController@update']);
Route::get('payments/{id}/delete', array('as' => 'payments.delete', 'uses' => 'PaymentController@getDelete'));
Route::get('payments/{id}/confirm-delete', array('as' => 'payments.confirm-delete', 'uses' => 'PaymentController@getModalDelete'));
Route::get('payments/{payments}', ['as'=> 'payments.show', 'uses' => 'PaymentController@show']);
Route::get('payments/{payments}/edit', ['as'=> 'payments.edit', 'uses' => 'PaymentController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('payments', ['as'=> 'payments.index', 'uses' => 'PaymentController@index']);
Route::post('payments', ['as'=> 'payments.store', 'uses' => 'PaymentController@store']);
Route::get('payments/create', ['as'=> 'payments.create', 'uses' => 'PaymentController@create']);
Route::put('payments/{payments}', ['as'=> 'payments.update', 'uses' => 'PaymentController@update']);
Route::patch('payments/{payments}', ['as'=> 'payments.update', 'uses' => 'PaymentController@update']);
Route::get('payments/{id}/delete', array('as' => 'payments.delete', 'uses' => 'PaymentController@getDelete'));
Route::get('payments/{id}/confirm-delete', array('as' => 'payments.confirm-delete', 'uses' => 'PaymentController@getModalDelete'));
Route::get('payments/{payments}', ['as'=> 'payments.show', 'uses' => 'PaymentController@show']);
Route::get('payments/{payments}/edit', ['as'=> 'payments.edit', 'uses' => 'PaymentController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('bookings', ['as'=> 'bookings.index', 'uses' => 'BookingController@index']);
Route::post('bookings', ['as'=> 'bookings.store', 'uses' => 'BookingController@store']);
Route::get('bookings/create', ['as'=> 'bookings.create', 'uses' => 'BookingController@create']);
Route::put('bookings/{bookings}', ['as'=> 'bookings.update', 'uses' => 'BookingController@update']);
Route::patch('bookings/{bookings}', ['as'=> 'bookings.update', 'uses' => 'BookingController@update']);
Route::get('bookings/{id}/delete', array('as' => 'bookings.delete', 'uses' => 'BookingController@getDelete'));
Route::get('bookings/{id}/confirm-delete', array('as' => 'bookings.confirm-delete', 'uses' => 'BookingController@getModalDelete'));
Route::get('bookings/{bookings}', ['as'=> 'bookings.show', 'uses' => 'BookingController@show']);
Route::get('bookings/{bookings}/edit', ['as'=> 'bookings.edit', 'uses' => 'BookingController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('soldbooks', ['as'=> 'soldbooks.index', 'uses' => 'SoldbookController@index']);
Route::post('soldbooks', ['as'=> 'soldbooks.store', 'uses' => 'SoldbookController@store']);
Route::get('soldbooks/create', ['as'=> 'soldbooks.create', 'uses' => 'SoldbookController@create']);
Route::put('soldbooks/{soldbooks}', ['as'=> 'soldbooks.update', 'uses' => 'SoldbookController@update']);
Route::patch('soldbooks/{soldbooks}', ['as'=> 'soldbooks.update', 'uses' => 'SoldbookController@update']);
Route::get('soldbooks/{id}/delete', array('as' => 'soldbooks.delete', 'uses' => 'SoldbookController@getDelete'));
Route::get('soldbooks/{id}/confirm-delete', array('as' => 'soldbooks.confirm-delete', 'uses' => 'SoldbookController@getModalDelete'));
Route::get('soldbooks/{soldbooks}', ['as'=> 'soldbooks.show', 'uses' => 'SoldbookController@show']);
Route::get('soldbooks/{soldbooks}/edit', ['as'=> 'soldbooks.edit', 'uses' => 'SoldbookController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('sms', ['as'=> 'sms.index', 'uses' => 'SmsController@index']);
Route::post('sms', ['as'=> 'sms.store', 'uses' => 'SmsController@store']);
Route::get('sms/create', ['as'=> 'sms.create', 'uses' => 'SmsController@create']);
Route::put('sms/{sms}', ['as'=> 'sms.update', 'uses' => 'SmsController@update']);
Route::patch('sms/{sms}', ['as'=> 'sms.update', 'uses' => 'SmsController@update']);
Route::get('sms/{id}/delete', array('as' => 'sms.delete', 'uses' => 'SmsController@getDelete'));
Route::get('sms/{id}/confirm-delete', array('as' => 'sms.confirm-delete', 'uses' => 'SmsController@getModalDelete'));
Route::get('sms/{sms}', ['as'=> 'sms.show', 'uses' => 'SmsController@show']);
Route::get('sms/{sms}/edit', ['as'=> 'sms.edit', 'uses' => 'SmsController@edit']);

});